version: "3.7"

services:
  demo:
    container_name: ls-partner-sdk-demo
    environment:
      - LS_ACCESS_TOKEN=${LS_ACCESS_TOKEN}
      - LS_PROJECT_NAME=Robin-Hipster-Shop
      - SPLIT_API_KEY=${SPLIT_API_KEY}
      - ROLLBAR_POST_ITEM_KEY=${ROLLBAR_POST_ITEM_KEY}
      - OTEL_EXPORTER_OTLP_SPAN_ENDPOINT=http://collector:55681/v1/traces
    image: ghcr.io/lightstep/lightstep-partner-toolkit-donut-shop:latest
    ports:
      - "8181:8181"

#  localtunnel-metric-webhook:
#    image: efrecon/localtunnel
#    depends_on:
#      - collector
#    command:
#      --local-host collector --port 7071
#
#  localtunnel-trace-webhook:
#    image: efrecon/localtunnel
#    depends_on:
#      - collector
#    command:
#      --local-host collector --port 7070

  collector:
    container_name: ls-partner-collector
    #image: ghcr.io/lightstep/lightstep-partner-toolkit-collector:latest
    # uncomment to build locally
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LS_ACCESS_TOKEN=${LS_ACCESS_TOKEN}
    volumes:
      - ./config/collector-config.yml:/etc/otel/config.yaml
    ports:
      - "13133:13133" # health_check
      - "55681:55681" # otlp http
      - "55680:55680" # otlp grpc
      - "7070:7070" # traces pipeline webhook
      - "7071:7071" # metrics pipeline webhook
